version: 2
jobs:
  build:
    docker:
      - image: 7896/civ3-workspace:2.0
      - image: mysql:5.7
        environment:
          MYSQL_HOST: 127.0.0.1
          MYSQL_DATABASE: homestead_test
          MYSQL_USER: homestead_test
          MYSQL_PASSWORD: secret
          MYSQL_ROOT_PASSWORD: root

    steps:
      - checkout
      - run: cp .env.example .env

      # composer cache
      - restore_cache:
          keys:
            - vendor-v1-{{ checksum "composer.lock" }}
      - run: composer install
      - save_cache:
          key: vendor-v1-{{ checksum "composer.lock" }}
          paths:
            - vendor

      # node cache
      - restore_cache:
          keys:
            - node-modules-v1-{{ checksum "yarn.lock" }}
      - run: cd resources/assets && yarn install
      - save_cache:
          key: node-modules-v1-{{ checksum "yarn.lock" }}
          paths:
            - resources/assets/node_modules

      # run
      - run: framgia-ci test-connect 127.0.0.1 3306 80
      - run: framgia-ci run --local
      - store_test_results:
          path: .framgia-ci-reports
